### ISSUE TITLE
Update Java, Node, Python and Go tutorials to use the new http-stream format and the latest FDK versions

### ISSUE THREAD

**Issue by sachin-pikle** [fnproject/tutorials#119]
When you run `fn init ...` the boilerplate should now generate a func.yaml with `format: http-stream`, and also newer FDK versions

**Comment by rikgibson** [comment]
I would remove all mention of the `format` property from these pages - it's going to disappear from `func.yaml` as soon as we can complete the work, and the link to "Open Function Format" is either broken (Ruby) or linking to a very-out-of-date page.

**Comment by michael-w-williams** [comment]
Opened a new issue to track the new request: https://github.com/fnproject/tutorials/issues/135
