### ISSUE TITLE
Formatting issue results in truncated command (Display runtime metrics tutorial)

### ISSUE THREAD

**Issue by sachin-pikle** [fnproject/tutorials#129]
Reported by @nishalad95 

Going through the fn tutorial ‘Display runtime metrics….’ and believe there is a discrepancy between the github markdown and the fnproject.io/tutorials pages. Not sure if you’re already aware of this …

1) 
```docker network inspect bridge -f '{{range .IPAM.Config}}{{.Gateway}}{{end}}'```

2) Within the “start grafana” section there is the same issue

the formatting for the above commands does not appear on the fnproject.io/tutorials page, not sure if the website is statically typed and requires additional formatting, but if users were to go through the tutorial through the website this section would not work.

**Comment by sachin-pikle** [comment]
![image](https://user-images.githubusercontent.com/29235281/47287627-8260c180-d610-11e8-916f-fc9f9c723544.png)

**Comment by sachin-pikle** [comment]
<img width="799" alt="image" src="https://user-images.githubusercontent.com/29235281/47287658-9f959000-d610-11e8-9f5b-7936b1d43419.png">

**Comment by nishalad95** [comment]
Additional issues picked up:

1) no option to set "Access" to ```proxy``` when configuring Grafana

2) ```fn deploy --local --app myapp``` uses the old fn routes and old version of func.yaml, users are promoted to use fn migrate to update to latest version of func.yaml, it would be better if the func.yaml file was the latest version

3) run.bash has a typo:
```curl localhost:8080/r/myapp/myfunc``` should be
```curl localhost:8080/t/myapp/myfunc```

**Comment by michael-w-williams** [comment]
Yes. This is documented by Issue 88: https://github.com/fnproject/tutorials/issues/88

Jekyll sees {{ blah }} as Jekyll variable with null values thus removing the content from the output. Think I have the solution, but I need to do more testing. Will update when I have something.

**Comment by michael-w-williams** [comment]
After much research the solution is to use HTML for those examples and replace the special characters with character entities. The text then looks good and is readable on both Github and in the Jekyll output as well.

Fixed with PR: https://github.com/fnproject/tutorials/pull/136
