### ISSUE TITLE
Container as a Function no longer valid

### ISSUE THREAD

**Issue by denismakogon** [fnproject/tutorials#137]
This tutorial: https://github.com/fnproject/tutorials/tree/master/ContainerAsFunction no longer works because of the cold functions and `format` are gone.
Best thing is to delete this tutorial. The best case: make it work with hotwrap.

**Comment by michael-w-williams** [comment]
Thanks Denis.  We are trying that issue here: https://github.com/fnproject/tutorials/issues/131. Shaun is going to update it with hotwrap.
