### ISSUE TITLE
FlowSaga stuck

### ISSUE THREAD

**Issue by eldermoraes** [fnproject/tutorials#145]
Hi there,

I'm using the Delabassee's fork to run the FlowSaga demo. But the execution is stuck and never ends.

In the travel dashboard it never reaches the "email" part and the FnFlow sometimes keeps waiting forever, sometimes it just stops the execution.

Any clue? I really would like to show this demo in a conference next week...

**Comment by delabassee** [comment]
Let's bring this to the Flow slack channel
https://fnproject.slack.com/messages/C7FKZ90F7

**Comment by eldermoraes** [comment]
Looks like I'd need an invitation to the workspace...

**Comment by delabassee** [comment]
It's a public slack channel.
