### ISSUE TITLE
Homebrew troubleshooting

### ISSUE THREAD

**Issue by denismakogon** [fnproject/tutorials#163]
Follow up of https://github.com/fnproject/cli/issues/549, there's a need to update the local package index before installing the CLI because it may give a feeling that Fn CLI releases are outdated.

**Comment by michael-w-williams** [comment]
Fixed this issue with following PRs:
* Main Fn repo: https://github.com/fnproject/fn/pull/1547
* Tutorials repo: https://github.com/fnproject/tutorials/pull/192

Also closing docs issue: https://github.com/fnproject/docs/issues/54
