### ISSUE TITLE
Need tutorial on passing xml and csv files to fn functions to process them.

### ISSUE THREAD

**Issue by ShravanGeek** [fnproject/tutorials#174]
Hi Team,

I having trouble on how to pass csv or xml files to our fn function to process them. Could you please provide any tutorials on that or at least a hint pointing to the solution, or any references please. Thanks a lot for your time.

**Comment by denismakogon** [comment]
Hi! Thanks for this query!
We’ll do our best. But for now, there’s what you can do right away:
1. Make your function download the file from the remote storage (via static files or S3-like).
2. Include your file into function’s image. For this you need to write a custom dockerfile that will include your file into the runtime stage.

If you’d need any help, please reach us in slack and do not hesitate to give us a start ;)

**Comment by ShravanGeek** [comment]
Thank you. Will post my technical questions at Slack.

**Comment by michael-w-williams** [comment]
Closing. Addressed in Slack. If you wish to discuss further, please reopen.
