### ISSUE TITLE
NodeJS Tutorial wrong instruction - fn init now generates triggers without the suffix 

### ISSUE THREAD

**Issue by AlexanderHodicke** [fnproject/tutorials#178]
Hi,

In the nodeJS tutorial is a small command in the chapter 'Invoke with curl':

curl -H "Content-Type: application/json" http://localhost:8080/t/nodeapp/nodefn-trigger

The suffix '-trigger' is not correct anymore.  fn init now generates triggers without the suffix.

BR

**Comment by michael-w-williams** [comment]
Fixed with PR <https://github.com/fnproject/tutorials/pull/180>

**Comment by AlexanderHodicke** [comment]
Looks great thanks!
