### ISSUE TITLE
FlowSaga demo scripts are half-broken

### ISSUE THREAD

**Issue by denismakogon** [fnproject/tutorials#19]
Following instructions from medium post i've ended up with following error during `scripts/configure.sh`:
```
./scripts/configure.sh
Error: No such container: fnserver
travel updated COMPLETER_BASE_URL with http://:8081
travel /flight/book updated FLIGHT_API_URL with http://:3001/flight
travel /flight/book updated FLIGHT_API_SECRET with shhhh
travel /flight/cancel updated FLIGHT_API_URL with http://:3001/flight
travel /flight/cancel updated FLIGHT_API_SECRET with shhhh
travel /hotel/book updated HOTEL_API_URL with http://:3001/hotel
travel /hotel/cancel updated HOTEL_API_URL with http://:3001/hotel
travel /car/book updated CAR_API_URL with http://:3001/car
travel /car/cancel updated CAR_API_URL with http://:3001/car
travel /email updated EMAIL_API_URL with http://:3001/email
```
configure script expects to find fnserver container running, which is not the common case, script should expect to get external configuration for those cases when fn server started with anything except `fn start`

**Comment by shaunsmith** [comment]
The instructions for the Flow Saga have the user run `start.sh` before `configure.sh`.  You *must* start fnserver so you can deploy and then once deployed the functions can be configured.  Deploy won't work if fnserver isn't already running so someone following along with the tutorial will fail before they even try to run `configure.sh`.
