### ISSUE TITLE
Error invoking function. status: 500 message: internal server error

### ISSUE THREAD

**Issue by Arvinzhu** [fnproject/tutorials#191]
```
[root@localhost simple-flow]# fn list apps
No apps found
NAME	ID	
[root@localhost simple-flow]# ls
func.yaml  pom.xml  src
[root@localhost simple-flow]# fn  --verbose build
Building image simple-flow:0.0.2 
FN_REGISTRY:  FN_REGISTRY is not set.
Current Context:  No context currently in use.
Sending build context to Docker daemon  11.26kB
Step 1/11 : FROM fnproject/fn-java-fdk-build:jdk11-1.0.100 as build-stage
 ---> 5686a17e235e
Step 2/11 : WORKDIR /function
 ---> Using cache
 ---> 7e96690920d7
Step 3/11 : ENV MAVEN_OPTS -Dhttp.proxyHost= -Dhttp.proxyPort= -Dhttps.proxyHost= -Dhttps.proxyPort= -Dhttp.nonProxyHosts= -Dmaven.repo.local=/usr/share/maven/ref/repository
 ---> Using cache
 ---> 989bba620e6b
Step 4/11 : ADD pom.xml /function/pom.xml
 ---> Using cache
 ---> fc82617b46d6
Step 5/11 : RUN ["mvn", "package", "dependency:copy-dependencies", "-DincludeScope=runtime", "-DskipTests=true", "-Dmdep.prependGroupId=true", "-DoutputDirectory=target", "--fail-never"]
 ---> Using cache
 ---> 3171bd32d903
Step 6/11 : ADD src /function/src
 ---> Using cache
 ---> 88c3e2093fbf
Step 7/11 : RUN ["mvn", "package"]
 ---> Using cache
 ---> 138e356edf96
Step 8/11 : FROM fnproject/fn-java-fdk:jre11-1.0.100
 ---> d41fcf9cdae1
Step 9/11 : WORKDIR /function
 ---> Using cache
 ---> 982c270e2e10
Step 10/11 : COPY --from=build-stage /function/target/*.jar /function/app/
 ---> Using cache
 ---> b433d6539758
Step 11/11 : CMD ["com.example.fn.HelloFunction::handleRequest"]
 ---> Using cache
 ---> 13e72cf01dc2
Successfully built 13e72cf01dc2
Successfully tagged simple-flow:0.0.2

Function simple-flow:0.0.2 built successfully.
[root@localhost simple-flow]# fn deploy --create-app --app flow101 --local
Successfully created app:  flow101
Deploying simple-flow to app: flow101
Bumped to version 0.0.3
Building image simple-flow:0.0.3 
Updating function simple-flow using image simple-flow:0.0.3...
Successfully created function: simple-flow with simple-flow:0.0.3
Successfully created trigger: simple-flow
Trigger Endpoint: http://localhost:8080/t/flow101/simple-flow
[root@localhost simple-flow]# echo 2 | fn invoke flow101 simple-flow
Error invoking function. status: 500 message: internal server error
```

系统：
`CentOS7.4`
版本：
```
[root@localhost hello]# fn version
Client version is latest version: 0.5.85
Server version:  0.3.731
```

simple-flow/src/main/java/com/example/fn/HelloFunction.java
```
package com.example.fn;

import com.fnproject.fn.api.flow.Flow;
import com.fnproject.fn.api.flow.Flows;
import com.fnproject.fn.runtime.flow.FlowFeature;
import com.fnproject.fn.api.FnFeature;

import java.io.Serializable;

@FnFeature(FlowFeature.class)
public class HelloFunction implements Serializable {

  public String handleRequest(int x) {
    Flow fl = Flows.currentFlow();

    return fl.completedValue(x)
      .thenApply( i -> i * 2)
      .thenApply( i -> "your number is: " + i + "\n")
      .get();
  }
}
```

simple-flow/func.yaml

```
schema_version: 20180708
name: simple-flow
version: 0.0.5
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.100
run_image: fnproject/fn-java-fdk:jre11-1.0.100
cmd: com.example.fn.HelloFunction::handleRequest
triggers:
- name: simple-flow
  type: http
  source: /simple-flow
```
Could you tell me how to  resolve this problem ?

**Comment by rdallman** [comment]
hi @Arvinzhu - could you possibly get logs to debug? `fn start --log-level=debug` will get logs from the function to `fn` stderr, likely just a bug in the simple flow program. thanks.

**Comment by mtjakobczyk** [comment]
Hi @rdallman, yesterday and today I hit the same problem for a Python app both on CentOS 7 as well as on Oracle Linux 7.7. The simplest way to reproduce is to... provision a VM on OCI, follow Fn installation tutorial and then Python app tutorial

**Comment by denismakogon** [comment]
But still, would you mind to paste logs here!

**Comment by mtjakobczyk** [comment]
Sure, I was on my way. It looks as if the newest (?) Docker (or more precisely runc) build introduces different defaults:
`error="API error (500): OCI runtime create failed: container_linux.go:348: starting container process caused \"process_linux.go:402: container init caused \\\"process_linux.go:367: setting cgroup config for procHooks process caused \\\\\\\"kernel memory accounting disabled in this runc build\\\\\\\"\\\"\": unknown" `

The entire dump:
`[opc@dev-vm pythonfn]$ fn invoke pythonapp pythonfn
Error invoking function. status: 500 message: internal server error
time="2019-09-07T07:58:01Z" level=error msg="error starting container" app_id=01DM5AZXXVNG8G00GZJ0000001 call_id=01DM5BNPY4NG8G00GZJ0000002 container=01DM5BNPY4NG8G00GZJ0000002 container_id=01DM5BNPY4NG8G00GZJ0000002 cpus= error="API error (500): OCI runtime create failed: container_linux.go:348: starting container process caused \"process_linux.go:402: container init caused \\\"process_linux.go:367: setting cgroup config for procHooks process caused \\\\\\\"kernel memory accounting disabled in this runc build\\\\\\\"\\\"\": unknown" fn_id=01DM5B22X3NG8G00GZJ0000002 idle_timeout=30 image="fndemouser/pythonfn:0.0.2" memory=256
time="2019-09-07T07:58:01Z" level=error msg="internal server error" action="server.handleFnInvokeCall)-fm" error="API error (500): OCI runtime create failed: container_linux.go:348: starting container process caused \"process_linux.go:402: container init caused \\\"process_linux.go:367: setting cgroup config for procHooks process caused \\\\\\\"kernel memory accounting disabled in this runc build\\\\\\\"\\\"\": unknown" fn_id=01DM5B22X3NG8G00GZJ0000002 stack="goroutine 47 [running]:\nruntime/debug.Stack(0xc4204842a0, 0x1051020, 0xc4204ca400)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/fnproject/fn/api/server.HandleErrorResponse(0x105be40, 0xc420494750, 0x7fab41bfe6c8, 0xc4200d3290, 0x1051020, 0xc4204ca400)\n\t/go/src/github.com/fnproject/fn/api/server/error_response.go:57 +0x57f\ngithub.com/fnproject/fn/api/server.handleErrorResponse(0xc4200d3290, 0x1051020, 0xc4204ca400)\n\t/go/src/github.com/fnproject/fn/api/server/error_response.go:25 +0xa9\ngithub.com/fnproject/fn/api/server.(*Server).handleFnInvokeCall(0xc4204240e0, 0xc4200d3290)\n\t/go/src/github.com/fnproject/fn/api/server/runner_fninvoke.go:53 +0x1da\ngithub.com/fnproject/fn/api/server.(*Server).(github.com/fnproject/fn/api/server.handleFnInvokeCall)-fm(0xc4200d3290)\n\t/go/src/github.com/fnproject/fn/api/server/server.go:1022 +0x34\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4200d3290)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/api/server.(*Server).runMiddleware(0xc4204240e0, 0xc4200d3290, 0x0, 0x0, 0x0)\n\t/go/src/github.com/fnproject/fn/api/server/middleware.go:42 +0x29f\ngithub.com/fnproject/fn/api/server.(*Server).rootMiddlewareWrapper.func1(0xc4200d3290)\n\t/go/src/github.com/fnproject/fn/api/server/middleware.go:32 +0x52\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4200d3290)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/api/server.panicWrap(0xc4200d3290)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:189 +0x51\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4200d3290)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/api/server.panicWrap(0xc4200d3290)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:189 +0x51\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4200d3290)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/api/server.apiMetricsWrap.func1.1(0xc4200d3290)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:153 +0x31a\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4200d3290)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/api/server.traceWrap(0xc4200d3290)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:96 +0x5ae\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4200d3290)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/api/server.loggerWrap(0xc4200d3290)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:206 +0x18e\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4200d3290)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc4200a98c0, 0xc4200d3290)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/gin.go:361 +0x586\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc4200a98c0, 0x105b780, 0xc420431c70, 0xc4204aa100)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/gin.go:326 +0x153\ngithub.com/fnproject/fn/vendor/go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP(0xc420430a50, 0x105b780, 0xc420431c70, 0xc4201ece00)\n\t/go/src/github.com/fnproject/fn/vendor/go.opencensus.io/plugin/ochttp/server.go:86 +0x1c8\nnet/http.serverHandler.ServeHTTP(0xc4201d4f70, 0x105a680, 0xc4204242a0, 0xc4201ece00)\n\t/usr/local/go/src/net/http/server.go:2697 +0xbc\nnet/http.(*conn).serve(0xc4201a1860, 0x105bd80, 0xc42047c640)\n\t/usr/local/go/src/net/http/server.go:1830 +0x651\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2798 +0x27b\n"`

**Comment by denismakogon** [comment]
Just as I suspected, newer version of runc on cents/oracle/redhat comes without memory accounting enabled.
So, there are two paths to follow:
- use Debian
- use docker-in-docker Fn image

Let us know which option you’d pick.

**Comment by mtjakobczyk** [comment]
Well... if I understand correct it seems Fn does not work on newer CentOS or Oracle Linux releases... is there any fnproject/fn issue for that?

**Comment by mtjakobczyk** [comment]
All in all, my understanding is that Fn does not work on newer CentOS or Oracle Linux. 
Using Debian or docker-in-docker Fn image would rather be workarounds, wouldn't they?

**Comment by mtjakobczyk** [comment]
https://github.com/fnproject/fn/issues/1520

**Comment by Arvinzhu** [comment]
Error Log： 
```
time="2019-09-09T01:59:43Z" level=error msg="error starting container" app_id=01DM9VN16MNG8G00GZJ0000001 call_id=01DM9VZ31VNG8G00GZJ0000007 container=01DM9VZ31VNG8G00GZJ0000007 container_id=01DM9VZ31VNG8G00GZJ0000007 cpus= error="API error (500): OCI runtime create failed: container_linux.go:345: starting container process caused \"process_linux.go:430: container init caused \\\"process_linux.go:396: setting cgroup config for procHooks process caused \\\\\\\"kernel memory accounting disabled in this runc build\\\\\\\"\\\"\": unknown" fn_id=01DM9VN1K9NG8G00GZJ0000002 idle_timeout=30 image="arvinzhujun/simple-flow:0.0.2" memory=128
```

```
time="2019-09-09T01:59:43Z" level=error msg="internal server error" action="server.handleFnInvokeCall)-fm" error="API error (500): OCI runtime create failed: container_linux.go:345: starting container process caused \"process_linux.go:430: container init caused \\\"process_linux.go:396: setting cgroup config for procHooks process caused \\\\\\\"kernel memory accounting disabled in this runc build\\\\\\\"\\\"\": unknown" fn_id=01DM9VN1K9NG8G00GZJ0000002 stack="goroutine 163 [running]:\nruntime/debug.Stack(0xc4204a9bc0, 0x1051020, 0xc4200fdc00)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/fnproject/fn/api/server.HandleErrorResponse(0x105be40, 0xc42019a240, 0x7f59f73a6488, 0xc4205740b0, 0x1051020, 0xc4200fdc00)\n\t/go/src/github.com/fnproject/fn/api/server/error_response.go:57 +0x57f\ngithub.com/fnproject/fn/api/server.handleErrorResponse(0xc4205740b0, 0x1051020, 0xc4200fdc00)\n\t/go/src/github.com/fnproject/fn/api/server/error_response.go:25 +0xa9\ngithub.com/fnproject/fn/api/server.(*Server).handleFnInvokeCall(0xc4204a20e0, 0xc4205740b0)\n\t/go/src/github.com/fnproject/fn/api/server/runner_fninvoke.go:53 +0x1da\ngithub.com/fnproject/fn/api/server.(*Server).(github.com/fnproject/fn/api/server.handleFnInvokeCall)-fm(0xc4205740b0)\n\t/go/src/github.com/fnproject/fn/api/server/server.go:1022 +0x34\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4205740b0)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/api/server.(*Server).runMiddleware(0xc4204a20e0, 0xc4205740b0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/fnproject/fn/api/server/middleware.go:42 +0x29f\ngithub.com/fnproject/fn/api/server.(*Server).rootMiddlewareWrapper.func1(0xc4205740b0)\n\t/go/src/github.com/fnproject/fn/api/server/middleware.go:32 +0x52\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4205740b0)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/api/server.panicWrap(0xc4205740b0)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:189 +0x51\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4205740b0)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/api/server.panicWrap(0xc4205740b0)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:189 +0x51\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4205740b0)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/api/server.apiMetricsWrap.func1.1(0xc4205740b0)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:153 +0x31a\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4205740b0)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/api/server.traceWrap(0xc4205740b0)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:96 +0x5ae\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4205740b0)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/api/server.loggerWrap(0xc4205740b0)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:206 +0x18e\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4205740b0)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc42043a7e0, 0xc4205740b0)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/gin.go:361 +0x586\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc42043a7e0, 0x105b780, 0xc4204e0960, 0xc42015a100)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/gin.go:326 +0x153\ngithub.com/fnproject/fn/vendor/go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP(0xc42020c190, 0x105b780, 0xc4204e0960, 0xc4202baa00)\n\t/go/src/github.com/fnproject/fn/vendor/go.opencensus.io/plugin/ochttp/server.go:86 +0x1c8\nnet/http.serverHandler.ServeHTTP(0xc420434dd0, 0x105a680, 0xc42026a000, 0xc4202baa00)\n\t/usr/local/go/src/net/http/server.go:2697 +0xbc\nnet/http.(*conn).serve(0xc420246000, 0x105bd80, 0xc4204f71c0)\n\t/usr/local/go/src/net/http/server.go:1830 +0x651\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2798 +0x27b\n"
```

**Comment by Arvinzhu** [comment]
Error log :
`
time="2019-09-09T01:59:43Z" level=error msg="error starting container" app_id=01DM9VN16MNG8G00GZJ0000001 call_id=01DM9VZ31VNG8G00GZJ0000007 container=01DM9VZ31VNG8G00GZJ0000007 container_id=01DM9VZ31VNG8G00GZJ0000007 cpus= error="API error (500): OCI runtime create failed: container_linux.go:345: starting container process caused \"process_linux.go:430: container init caused \\\"process_linux.go:396: setting cgroup config for procHooks process caused \\\\\\\"kernel memory accounting disabled in this runc build\\\\\\\"\\\"\": unknown" fn_id=01DM9VN1K9NG8G00GZJ0000002 idle_timeout=30 image="arvinzhujun/simple-flow:0.0.2" memory=128
`

`
time="2019-09-09T01:59:43Z" level=error msg="internal server error" action="server.handleFnInvokeCall)-fm" error="API error (500): OCI runtime create failed: container_linux.go:345: starting container process caused \"process_linux.go:430: container init caused \\\"process_linux.go:396: setting cgroup config for procHooks process caused \\\\\\\"kernel memory accounting disabled in this runc build\\\\\\\"\\\"\": unknown" fn_id=01DM9VN1K9NG8G00GZJ0000002 stack="goroutine 163 [running]:\nruntime/debug.Stack(0xc4204a9bc0, 0x1051020, 0xc4200fdc00)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/fnproject/fn/api/server.HandleErrorResponse(0x105be40, 0xc42019a240, 0x7f59f73a6488, 0xc4205740b0, 0x1051020, 0xc4200fdc00)\n\t/go/src/github.com/fnproject/fn/api/server/error_response.go:57 +0x57f\n
`

**Comment by Arvinzhu** [comment]
[fnproject/fn#1502](https://github.com/fnproject/fn/issues/1520) 
This problem has resolved.
I had changed the `docker`  `docker-cli` and `containerd.io`  version 。

`
[root@localhost fn]# docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:22 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:19:08 2018
  OS/Arch:          linux/amd64
  Experimental:     false
`

[containerd.io-1.2.2-3.3.el7.x86_64.rpm](https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.2-3.3.el7.x86_64.rpm)

**Comment by rdallman** [comment]
@denismakogon do you remember why we didn't do dind for `fn start` by default? mac or windows it doesn't work maybe? also lose any images between `fn start` and can't use local images (could cause lots of confusion for users, the latter), I can't think of much else... maybe we should make this more accessible from `fn start` instead of requiring users to dig through our docs for the docker command without the host docker sock mounting? something like `fn start --dind`, we could maybe try to default to it on centos/oel too I guess, an option at least. cc @shaunsmith

**Comment by rdallman** [comment]
thanks for logs, yea, I missed the bit about centos, kernel memory accounting thing is killing default experience there. hopefully we can figure something out, open to ideas here, I haven't researched much about centos/runc specific resolutions, it seems sub par to require users to install a different docker version but it's possible we have to just add that step too. some other ideas above.

**Comment by denismakogon** [comment]
@rdallman exactly because of docker for Mac/win.
This problem might be solved in two ways:
1. Use dind.
2. Keep telling people to downgrade containers.io package.

I’d pick DIND.

**Comment by aaraodeo** [comment]
To try to resolve "kernel memory accounting disabled in this runc build" issue
I tried running with dind
As root user:
setenforce permissive
Then
docker run --privileged --rm --name fns -it -v $PWD/data:/app/data -p 8080:8080 fnproject/fnserver 

The fn server started but its unable to pull the local images created using following cmd:
fn deploy --app myapp --local
fn invoke myapp hello
Any resolution for this issue? I am facing same issue in oracle linux 7.8 kernel 4.14.35-1902.6.6.el7uek.x86_64.
docker version: 19.03.11-ol
fn version:
Client version is latest version: 0.5.99
Server version:  0.3.749

Kindly confirm i think in dind mode the images can only be pulled remotely from an accessible docker registry or let me know if any workaround is available to local images.

We cannot use -v /var/run/docker.sock:/var/run/docker.sock in this case.

**Comment by rdallman** [comment]
@aaraodeo you could mount just the images in, doing something like `-v /var/lib/docker:/var/lib/docker` (or more precisely, `/var/lib/docker/image/overlay2`), there's likely more ways to get the local images in from disk if something else tickles your fancy (tarball, build inside, etc). you could also run a local registry, put the images there, and then connect the fn container to the registry [container] so that it could pull images from there (there's a number of ways to do this, as well, the easiest being to run both on `--net=host` if you're not doing anything serious).

**Comment by hb-lee** [comment]
I met the similar problem with the following error:

```
INFO[2024-12-10T10:03:54Z] container wait error, sending error to client  action="server.handleFnInvokeCall)-fm" app_id=01JEQX66Q4NG8G00GZJ0000001 call_id=01JER0CXWVNG8G00GZJ0000001 error="API error (500): failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting rootfs as readonly: mount /, flags: 0x1021: device or resource busy: unknown" fn_id=01JEQX6W7ENG8G00GZJ0000002
ERRO[2024-12-10T10:03:54Z] internal server error                         action="server.handleFnInvokeCall)-fm" error="API error (500): failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting rootfs as readonly: mount /, flags: 0x1021: device or resource busy: unknown" fn_id=01JEQX6W7ENG8G00GZJ0000002 stack="goroutine 14 [running]:\nruntime/debug.Stack(0xc42015a310, 0x10852c0, 0xc42022bdc0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/fnproject/fn/api/server.HandleErrorResponse(0x10902a0, 0xc4205a4840, 0x7fe283617150, 0xc4201a2000, 0x10852c0, 0xc42022bdc0)\n\t/go/src/github.com/fnproject/fn/api/server/error_response.go:57 +0x57f\ngithub.com/fnproject/fn/api/server.handleErrorResponse(0xc4201a2000, 0x10852c0, 0xc42022bdc0)\n\t/go/src/github.com/fnproject/fn/api/server/error_response.go:25 +0xa9\ngithub.com/fnproject/fn/api/server.(*Server).handleFnInvokeCall(0xc4204ce0e0, 0xc4201a2000)\n\t/go/src/github.com/fnproject/fn/api/server/runner_fninvoke.go:53 +0x1da\ngithub.com/fnproject/fn/api/server.(*Server).(github.com/fnproject/fn/api/server.handleFnInvokeCall)-fm(0xc4201a2000)\n\t/go/src/github.com/fnproject/fn/api/server/server.go:1022 +0x34\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4201a2000)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/api/server.(*Server).runMiddleware(0xc4204ce0e0, 0xc4201a2000, 0x0, 0x0, 0x0)\n\t/go/src/github.com/fnproject/fn/api/server/middleware.go:42 +0x29f\ngithub.com/fnproject/fn/api/server.(*Server).rootMiddlewareWrapper.func1(0xc4201a2000)\n\t/go/src/github.com/fnproject/fn/api/server/middleware.go:32 +0x52\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4201a2000)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/api/server.panicWrap(0xc4201a2000)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:197 +0x51\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4201a2000)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/api/server.panicWrap(0xc4201a2000)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:197 +0x51\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4201a2000)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/api/server.apiMetricsWrap.func1.1(0xc4201a2000)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:158 +0x316\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4201a2000)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/api/server.traceWrap(0xc4201a2000)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:101 +0x5ae\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4201a2000)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/api/server.loggerWrap(0xc4201a2000)\n\t/go/src/github.com/fnproject/fn/api/server/gin_middlewares.go:214 +0x18e\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4201a2000)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/context.go:108 +0x43\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc4204905a0, 0xc4201a2000)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/gin.go:361 +0x586\ngithub.com/fnproject/fn/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc4204905a0, 0x108fbe0, 0xc4202467d0, 0xc420480400)\n\t/go/src/github.com/fnproject/fn/vendor/github.com/gin-gonic/gin/gin.go:326 +0x153\ngithub.com/fnproject/fn/vendor/go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP(0xc4202460f0, 0x108fbe0, 0xc4202467d0, 0xc420162b00)\n\t/go/src/github.com/fnproject/fn/vendor/go.opencensus.io/plugin/ochttp/server.go:86 +0x1c8\nnet/http.serverHandler.ServeHTTP(0xc42047e9c0, 0x108ea60, 0xc42019e000, 0xc420162b00)\n\t/usr/local/go/src/net/http/server.go:2697 +0xbc\nnet/http.(*conn).serve(0xc4201d8000, 0x10901e0, 0xc420598100)\n\t/usr/local/go/src/net/http/server.go:1830 +0x651\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2798 +0x27b\n"

```

How can we fix this?
