### ISSUE TITLE
page containing the examples

### ISSUE THREAD

**Issue by Daniel-Dos** [fnproject/tutorials#27]
Dear,

would not it be interesting to have a page on the site https://fnproject.io/ containing these tutorials in a cleaner way?

Thanks.

**Comment by shaunsmith** [comment]
Yes, we're looking at generating Tutorial content for fnproject.io using github pages.

**Comment by Daniel-Dos** [comment]
thanks.

**Comment by michael-w-williams** [comment]
See: http://fnproject.io/tutorials/. Its all up there.

**Comment by Daniel-Dos** [comment]
very good @michael-w-williams .

thanks.
