### ISSUE TITLE
Could not download fn from github

### ISSUE THREAD

**Issue by lxghz** [fnproject/tutorials#40]
Hi : 
 When I download fn from github, it match error "curl: (23) Failed writing body (0 != 16360)"
Would you please confirm whether script is correct?
  I run the shell as below:
curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh

**Comment by sachin-pikle** [comment]
I just tried it again and it works fine for me on macbook. Which OS are you using?

$ curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh
Password:
fn version 0.4.61

        ______
       / ____/___
      / /_  / __ \
     / __/ / / / /
    /_/   /_/ /_/`

**Comment by sachin-pikle** [comment]
Hi @lxghz are you still having trouble downloading Fn? If not, can we close this issue?

**Comment by skinowski** [comment]
@lxghz From your error message, it looks like you might not have write privileges to /tmp.

**Comment by skinowski** [comment]
@lxghz could you please post some details on your os environment and disk?
