### ISSUE TITLE
Update Fn Go Introduction Tutorial to use --runtime and JSON Data

### ISSUE THREAD

**Issue by michael-w-williams** [fnproject/tutorials#42]
Update the Fn Go introduction tutorial to use `fn init --runtime go gofn` to generate hello function and JSON data.

* [x] Create a branch to make changes 
* [x] Update the tutorial 
* [x] Submit a PR https://github.com/fnproject/tutorials/pull/41
* [x] Merge and close PR https://github.com/fnproject/tutorials/pull/41

**Comment by sachin-pikle** [comment]
Shaun merged PR #41. I have updated the 4th check box above and am closing this one.
