### ISSUE TITLE
Update Fn Java Introduction Tutorial to use --runtime and JSON Data

### ISSUE THREAD

**Issue by michael-w-williams** [fnproject/tutorials#43]
Update the Fn Java introduction tutorial to use `fn init --runtime java javafn` to generate hello function and JSON data.

* [x] Create a branch to make changes 
* [x] Update the tutorial 
* [x] Submit a PR 
* [x] Merge and close PR

**Comment by sachin-pikle** [comment]
@michael-w-williams our current Java tutorial https://github.com/fnproject/tutorials/blob/master/JavaFDKIntroduction/README.md already uses `fn init --runtime java javafn` so this part is already implemented.

Regarding the second part - use of `format: json`, the Java FDK currently uses `format: http`. See this thread in Slack https://fnproject.slack.com/archives/C7FKW83GV/p1520351629000792 for more details. As per @treeder "JSON will take over HTTP it looks like, but until the FDK supports it, you have to use what the FDK uses". So we should keep an eye on the Java FDK project.

**Comment by michael-w-williams** [comment]
@sachin-pikle Good point! So this one is essentially done to.
