### ISSUE TITLE
Need "Fn Introduction Tutorial" tutorial in Node.js

### ISSUE THREAD

**Issue by sachin-pikle** [fnproject/tutorials#45]
Use `fn init --runtime node`

Make sure we’re consistent with the input format (json), usage of FDK’s in boilerplate gen, etc. 

Document inconsistencies in experience i.e. if an fn init doesn’t give us the right set of files, raise that as an issue and document. Right now it’s inconsistent across the board. And we need this fixed over the next few weeks.

**Comment by michael-w-williams** [comment]
Completed. See: https://github.com/fnproject/tutorials/pull/56.
