### ISSUE TITLE
Improvements to fnproject.io/tutorials (Jekyll template)

### ISSUE THREAD

**Issue by sachin-pikle** [fnproject/tutorials#50]
A few small observations about http://fnproject.io/tutorials page:

- [x] Can we make the tutorial name font a bit smaller, and not blue because it looks like a link?
- [x] Also something doesnt’ feel right about the way the layout is setup in the tutorials page. It’s like a really big title for each tutorial, then a link. Maybe if there were a bunch of links to each, it’d make more sense. Anything that only has one link shouldn’t be a group
- [x] The "Tutorials" link on https://github.com/fnproject/fn/blob/master/README.md points to fnproject.com/tutorials. Needs to point to fnproject.io/tutorials

Moved button and nav work to a separate Issue (https://github.com/fnproject/tutorials/issues/59).

**Comment by michael-w-williams** [comment]
Please see https://michael-w-williams.github.io/tutorials/ for a mockup with the proposed. Changes.

**Comment by sachin-pikle** [comment]
Looks a lot better now!

**Comment by carimura** [comment]
nice! +1.

**Comment by michael-w-williams** [comment]
I moved the button and nav work to a new issue. Closing this one.
