### ISSUE TITLE
Update existing Tutorials to use Installation Tutorial

### ISSUE THREAD

**Issue by michael-w-williams** [fnproject/tutorials#73]
Enhance all the intro tutorials to use the installation tutorial.

**Comment by sachin-pikle** [comment]
At least there that I noticed, 
1) Java Intro tutorial
2) Create a Function from Docker Image
3) Monitor Fn metrics with Grafana and Prometheus tutorial 

Need to update the to point to the new "Install and Start Fn Tutorial".

**Comment by michael-w-williams** [comment]
Closing. Will replace with more specific issues.
